name: On Delete

on:
  delete:

  workflow_dispatch:

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  on-delete:
    name: On delete
    runs-on: ubuntu-latest
    steps:
      - name: Get branch name
        id: branch-name
        uses: tj-actions/branch-names@v5.1
      - name: Do Something With it
        id: do-sommat
        run: echo "Branch is ${{ steps.branch-name.outputs.ref_branch }}"

